version: "3.8"
services:
#======================================
#======= friday-booster service =======
#======================================
  friday-booster:

#==================================
#======= PostgreSQL service =======
#==================================
  PostgreSQL:

#========================
#======= networks =======
#========================
networks:
  friday_booster_network:
#=======================
#======= volumes =======
#=======================
volumes:
  db-data:
  log-data:
